### ISSUE TITLE
Add Chatbot Feature to Hotel Management System Website

### ISSUE THREAD

**Issue by amanver45** [Yorichiiii22/hotel-Management-site-#19]
I want to integrate a chatbot into our Hotel Management System website to enhance customer support and provide a better user experience. The chatbot will assist visitors with common queries such as room availability, pricing, booking process, amenities, and more.

**Comment by Yorichiiii22** [comment]
@amanver45 do the best!

**Comment by amanver45** [comment]
@Yorichiiii22 gssoc ext albel are not added

**Comment by amanver45** [comment]
pls also add level
@Yorichiiii22

**Comment by HarshS16** [comment]
@Yorichiiii22 Are you registered as an admin at Gssoc? Because none of my PRs are updated on gssoc and they're saying that this project is not a part of gssoc

**Comment by Yorichiiii22** [comment]
@HarshS16  it is showing in gssoc

**Comment by amanver45** [comment]
@Yorichiiii22 its not showing  @HarshS16 THIS project is not part of gssoc ext
![Screenshot 2024-10-25 193323](https://github.com/user-attachments/assets/983544fe-fb19-4fbf-95c3-c416da82b60c)

**Comment by HarshS16** [comment]
> @Yorichiiii22 its not showing @HarshS16 THIS project is not part of gssoc ext ![Screenshot 2024-10-25 193323](https://private-user-images.githubusercontent.com/183379031/380196941-983544fe-fb19-4fbf-95c3-c416da82b60c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjk4NjkwMjIsIm5iZiI6MTcyOTg2ODcyMiwicGF0aCI6Ii8xODMzNzkwMzEvMzgwMTk2OTQxLTk4MzU0NGZlLWZiMTktNGZiZi05NWMzLWM0MTZkYTgyYjYwYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMDI1JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTAyNVQxNTA1MjJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jNGY3NDYyMGU1OGY4ZWUxMWM3OGM3OWE1NDQxNmJjNWQ0YmNkYTBjY2M2ZTRjMmU5M2JjZjY3NjBhNGI3MTU1JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.BVNrSY-0V_J-suMnCPb5D172E_wdFBiGDNQcvjHNn5Y)

Yes exactly!! @Yorichiiii22 Don't mislead developers bro :/

**Comment by Yorichiiii22** [comment]
@HarshS16 very sorry if it is not showing but it was showing in hacktoberfest and previously I have done gssoc-ext and it was accepting, but it's not showing now sorry for that but I was not misleading...

**Comment by Yorichiiii22** [comment]
It is accepting hacktoberfest if you want you can contribute to it

**Comment by HarshS16** [comment]
> It is accepting hacktoberfest if you want you can contribute to it

![image](https://github.com/user-attachments/assets/27323fe1-0e5f-4c7f-a0c2-0032ea1a633a)

:)

**Comment by Yorichiiii22** [comment]
Accepting!
