### ISSUE TITLE
Add Restaurant Subscription Plans for Regular Users 

### ISSUE THREAD

**Issue by Anshikapal05** [Yorichiiii22/hotel-Management-site-#26]
By Developing offer subscription plans where customers can get monthly deliveries of their favourite food or exclusive deals on new arrivals. I will help to grow the work. A subscription model with various tiers like basic or premium will be set up.
Labels:  hacktoberfest-accepted

**Comment by Anshikapal05** [comment]
@Yorichiiii22 could you please assign to me? it would be really helpful!
thank you

**Comment by Yorichiiii22** [comment]
@Anshikapal05  great idea
