### ISSUE TITLE
Content: Adding real content to the website

### ISSUE THREAD

**Issue by HarshS16** [Yorichiiii22/hotel-Management-site-#9]
The website has a lot of spelling mistakes and dummy data , let me add real content and images to the website to make it look authentic. 
![image](https://github.com/user-attachments/assets/9da902c6-29d7-4f65-91f3-301a2ddfb36f)
![image](https://github.com/user-attachments/assets/7261db82-b59a-441e-b879-31e9e7e5ceb9)

**Comment by HarshS16** [comment]
@Yorichiiii22 are you working on the website? There seems to be something wrong with it...

**Comment by Yorichiiii22** [comment]
@HarshS16 yes i am working on the issues

**Comment by HarshS16** [comment]
@Yorichiiii22 Shall I add food items and description based on my opinions?

**Comment by Yorichiiii22** [comment]
@HarshS16  ya you can!
